_BASE_: "cascade_mask_rcnn_R_50_FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  ROI_HEADS:
    USE_DROPLOSS: False
SOLVER:
  IMS_PER_BATCH: 0
  IMS_PER_BATCH_LABEL: 8
  IMS_PER_BATCH_UNLABEL: 8
DATASETS:
  CROSS_DATASET: True
  TRAIN: ("",)
  TRAIN_LABEL: ("cls_agnostic_coco_train+unlabeled_pseudo",)
  TRAIN_UNLABEL: ("cls_agnostic_coco_train+unlabeled_pseudo",)
  TEST: ("cls_agnostic_coco+lvis_val",)
DATALOADER:
  COPY_PASTE: False
SEMISUPNET:
  TRAINER: "mean_teacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 0
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 2.0
  SUP_LOSS_WEIGHT: 1.0
  LOSS_WEIGHT_SCHEDULE: "cosine"
  REMOVE_ERASED_OBJECTS: False
TEST:
  PRECISE_BN:
    ENABLED: False
